---
--- Generated by dotalk.cn
--- Created by yongze.chen
--- DateTime: 2018/9/23 下午11:52
---

--请求头
ngx.header["X-Server-By"] = 'yongze.chen'
ngx.header['Content-Type']="text/html;charset=UTF-8"

--403 Forbidden
--ngx.exit(200)
local cjson = require("cjson")

local obj = {
    id = 1,
    name = "zhangsan",
    age = nil,
    is_male = false,
    hobby = {"film", "music", "read"}
}

local str = cjson.encode(obj)
ngx.say(str)
ngx.exit(200)