---
--- Generated by dotalk.cn
--- Created by yongze.chen
--- DateTime: 2018/9/23 下午10:23
---

--local tmpKey = redis.call('HGET', KEYS[1], KEYS[2]);
--return redis.call('SET', KEYS[1],ARGV[2]);
print(3232131)